# Generated by Django 4.2.13 on 2024-05-20 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentabancaria',
            old_name='cuenta',
            new_name='usuario',
        ),
    ]
