# Generated by Django 4.2.13 on 2024-05-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaBancaria', '0002_rename_cuenta_cuentabancaria_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='numeroCuenta',
            field=models.TextField(default='d81cuq6YZ7', max_length=10, unique=True),
        ),
    ]
