# Generated by Django 4.2.13 on 2024-05-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TarjetaCredito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetacredito',
            name='numero',
            field=models.TextField(default='Vf0EDvi6ov', max_length=10, unique=True),
        ),
    ]
